services:
  es01:
    image: elasticsearch:8.17.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200 | grep 'You Know, for Search'"]
      start_period: 1s
      retries: 120
      timeout: 2s
      interval: 1s

  kibana:
    image: kibana:8.17.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    depends_on:
      es01:
        condition: service_healthy
